apiRules:
  - exclude:
      uidRegex: \.Migrations\.
  - exclude:
      uidRegex: \.Internal\.
  - exclude:
      hasAttribute:
        uid: System.Runtime.CompilerServices.CompilerGeneratedAttribute
